'use strict';
window.$ = require('../../bower_components/jquery/dist/jquery.js');
window.jQuery = require('../../bower_components/jquery/dist/jquery.js');
window.Hammer = require('../../bower_components/materialize/js/hammer.min.js');
require('../../js/app');
require('../../js/controllers');
require('../../js/services');
require('../../js/filters');
require('../../js/factories');
require('../../js/directives');
