require('../../js/factories/userFactory');
require('../../js/factories/viewFactory');
require('../../js/factories/socketFactory');
require('../../js/factories/peerFactory');
require('../../js/factories/dbFactory');
//modals
require('../../js/factories/modals/newUser');
require('../../js/factories/modals/sendCryptiModal');
require('../../js/factories/modals/addDappModal');